export enum keanuTypes {
  GET_KEANU_IMAGE = "GET_KEANU_IMAGE",
  SET_KEANU_IMAGE_SUCCESS = "SET_KEANU_IMAGE_SUCCESS",
  SET_KEANU_IMAGE_LOADING = "SET_KEANU_IMAGE_LOADING",
  SET_KEANU_IMAGE_ERROR = "SET_KEANU_IMAGE_ERROR",
}
